# Generated by Django 4.1.2 on 2022-10-23 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(db_column='id_category', on_delete=django.db.models.deletion.DO_NOTHING, related_name='products', to='core.category'),
        ),
    ]
